"""make invoice vendor amount date nullable

Revision ID: 1a13e12b7aa6
Revises: 128ff12ef5f1
Create Date: 2026-09-06 11:53:54.890822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a13e12b7aa6'
down_revision: Union[str, Sequence[str], None] = '128ff12ef5f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'vendor',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('invoices', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('invoices', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('invoices', 'vendor',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
